spring:
  application:
    name: APIGATEWAY

server:
  port: 8086

#cloud:
#  gateway:
#    routes:
#      - id: ISSUE-LIST
#        uri: lb://ISSUE-LIST
#        predicates:
#          - Path=/issueList/**
#
#      - id: ADDPROJECT
#        uri: lb://ADDPROJECT
#        predicates:
#          - Path=/addNewProject/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
    fetch-registry: true
    register-with-eureka: true
